# 1. Python中的固定类型数组

内置的array模块可以用于创建统一类型的密集数组

In [1]:
import array

In [2]:
L = list(range(10))
"""'i' 是一个数据类型码，表示数据为整型"""
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 2. 从Python列表创建数组

In [3]:
import numpy as np

In [4]:
# 整型数组
np.array([1, 4, 2 ,5, 3])

array([1, 4, 2, 5, 3])

Numpy数组必须包含同一类型的数据，如果类型不匹配，Numpy将会向上转型

In [5]:
np.array([3.14, 4, 2, 3]) # 这里整型被转换为浮点型

array([3.14, 4.  , 2.  , 3.  ])

可以使用dtype关键字明确数组的数据类型

In [6]:
np.array([1, 2, 3 ,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [7]:
# 嵌套列表构成的多维数组
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# 3.从头创建数组

## 3.1 创建数组的值都是0的数组

In [8]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## 3.2 创建数组的值都是1的数组

In [9]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 3.3 创建数组的值全为指定值的数组

In [10]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [11]:
np.full((3, 5), 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

## 3.4 创建一个线性序列数组

In [12]:
np.arange(0, 20, 2)  # 与内置的range函数类似

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## 3.5 创建数值在范围内均匀分配的数组

In [13]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## 3.6 创建满足均匀分布随机数组

In [14]:
np.random.random((3, 3))  # 3 * 3的，在0~1均匀分布的数值

array([[0.18994471, 0.24080204, 0.27788575],
       [0.27519927, 0.19102626, 0.025082  ],
       [0.33740604, 0.93249559, 0.31695115]])

## 3.7 创建满足正态分布的随机数组

In [15]:
np.random.normal(0, 1, (3, 3))  # 创建一个均值为0， 标准差为1的 3 * 3 的满足正态分布的数组

array([[ 0.31194154,  0.346048  ,  1.40126978],
       [ 0.62326907,  0.55480253,  1.85336946],
       [-1.13994633,  0.28045145,  1.33995211]])

## 3.8 创建随机整数数组

In [16]:
np.random.randint(0, 10, (3, 3))

array([[9, 7, 6],
       [6, 1, 0],
       [9, 2, 7]])

## 3.9 创建单位矩阵

In [17]:
np.eye(3) # 创建3 * 3的单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 3.10 创建未初始化的数组

In [18]:
"""
数组的值是内存空间中的任意值
"""
np.empty(3)

array([1., 1., 1.])

# 4. Numpy中的标准数据类型

| 数据类型  | 描述                                              |
|-------|-------------------------------------------------|
| bool_ | 布尔值（True或False）， 用一个字节存储                        |
| int_  | 默认整型（类似于C语言中的lang， 通常情况下是int64或int32）           |
| intc  | 同C语言中的int相同（通常是int32或int64）                     |
| intp  | 用作索引的整型（和C语言的ssize_t相同，通常情况下是int32或int64）       |
| int8  | 字节（byte, 范围从-128到127）                           |
| int16 | 整型（范围从-32768到32767）                             |
| int32 | 整型（范围从-2147483648到2147483647）                   |
| int64 | 整型（范围从-9223372036854775808到9223372036854775807） |
| uint8 | 无符号整型（范围从0到255）                                 |
|uint16| 无符号整型（范围从0到65535）                               |
|uint32| 无符号整型（范围从0到4294967295）                          |
|uint64| 无符号整型（范围从0到18446744073709551615）                |
|float_| float64的简化形式                                    |
|float16| 半精度浮点型：符号比特位，5比特位指数（exponent），10比特位尾数（mantissa） |
|float32| 单精度浮点型：符号比特位，8比特位指数，23比特位尾数                     |
|float64| 双精度浮点型：符号比特位：11比特位指数，52比特位尾数                    |
|complex_| complex128的简化形式                                 |
|complex64| 复数，由两个32位浮点数表示                                  |
|complex128| 复数，由两个64位浮点数表示                                  |