# 1. Numpy数组的属性

使用Numpy的随机数生成器设置一组种子值，以确保每次程序执行时都生成同样的随机数组

In [60]:
import numpy as np
np.random.seed(0)  # 设置随机数种子

In [61]:
x1 = np.random.randint(10, size=6)  # 一维数组
x2 = np.random.randint(10, size=(3, 4))  # 二维数组
x3 = np.random.randint(10, size=(3, 4, 5))  # 三维数组

每个数组有ndim(数组的纬度)、shape(数组每个纬度的大小)和size(数组的总大小)属性：

In [62]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


数组的数据类型属性  dbyte

In [63]:
print("dtype:", x3.dtype)

dtype: int32


表示每个数组元素字节大小的属性itemsize，表示数组总字节大小的属性nbytes.  itemsize * size = nbytes

In [64]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "nbytes")

itemsize: 4 bytes
nbytes: 240 nbytes


# 2. 数组索引：获取单个元素

## 2.1 一维数组

In [65]:
x1

array([5, 0, 3, 3, 7, 9])

In [66]:
x1[0]

5

In [67]:
x1[4]

7

## 2.2 二维数组

In [68]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [69]:
x2[0, 0]

3

In [70]:
x2[2, 0]

1

In [71]:
x2[2, -1]

7

In [72]:
# 同样可以使用索引方式修改元素值
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [73]:
"""
Numpy数组是固定类型的。因此将浮点值插入一个整型数组时，浮点型会被截断成整型。
这种截断是自动完成的
"""

x1[0] = 3.14159  # 将被阶段
x1

array([3, 0, 3, 3, 7, 9])

# 3. 数组切片：获取子数组

Numpy为了获取数组的一个切片，可以使用以下方式
x[start:stop:step]
如果以上三个参数未指定，则会被分别设置成默认值start=0，stop=纬度的大小，step=1

## 3.1 一维子数组

In [74]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
x[:5]

array([0, 1, 2, 3, 4])

In [76]:
x[5:]

array([5, 6, 7, 8, 9])

In [77]:
x[4:7]

array([4, 5, 6])

In [78]:
x[::2]

array([0, 2, 4, 6, 8])

In [79]:
x[1::2]

array([1, 3, 5, 7, 9])

In [80]:
x[::-1]  # 在这个例子中，start参数和stop参数是默认被交换的

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [81]:
x[5::-2]

array([5, 3, 1])

## 3.2 多维子数组

多维切片也采用同样的方式处理，用逗号分割。

In [82]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [83]:
x2[:2, :3]  # 两行，三列

array([[12,  5,  2],
       [ 7,  6,  8]])

In [84]:
x2[:3, ::2]  # 所有行，每隔一列

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [85]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

## 3.3 获取数组的行和列

可以将索引和切片组合起来实现获取数组的单行和单列

In [86]:
print(x2[:, 0])  # x2的第一列

[12  7  1]


In [87]:
print(x2[0:])  # x2的第一行

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


在获取行时，出于语法的简洁考虑，可以省略空的切片

In [88]:
print(x2[0])  # 等于x2[0, :]

[12  5  2  4]


## 3.4 非副本视图的子数组

在Numpy中数组切片返回的是数组数据的视图，而不是数值数据的副本。因此修改切片抽取的子数组时，原始数组也会被修改

In [89]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [90]:
x2_sub = x2[:2, :2]  # 抽取子数组
print(x2_sub)

[[12  5]
 [ 7  6]]


In [91]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [92]:
print(x2)  # 可以看到原始数组也被修改了

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## 3.5 创建数组的副本

In [93]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [94]:
x2_sub_copy[0, 0] = 42  # 修改这个子数组，原始的数组不会被修改
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [95]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


# 4. 数组的变形

数组变形最灵活的实现方式是通过reshape()函数来实现

In [96]:
# 将数组 1 ~ 9放入一个3 * 3 的矩阵中
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


如果希望该方法可行，那么原始数组的大小必须和变形后的数组的大小一致。
如果满足这个条件，reshape方法将会用到原始数组的一个非副本视图。
在非连续的数数据缓存下，返回非副本视图往往不可能实现

另外一个常见的变形模式是将一个一维数组转变成二维的行或列的矩阵
可以通过reshape方法来实现
也可以在一个切片操作中利用newaxis关键字

In [97]:
x = np.array([1, 2, 3])

"""通过变形获得的行向量"""
x.reshape((1, 3))

array([[1, 2, 3]])

In [98]:
"""通过newaxis获得的行向量"""
x[np.newaxis, :]

array([[1, 2, 3]])

In [99]:
"""通过变形获得的列向量"""
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [100]:
"""通过newaxis获得的列向量"""
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

# 5. 数组的拼接和分裂

## 5.1 数组的拼接

有时需要将多个数组合并为一个，或将一个数组分裂成多个

拼接和连接Numpy中的两个数组主要由np.concatenate,np.vstack和np.hstack例程实现

In [101]:
"""np.concatenate将数组元组或数组列表作为第一个参数"""
x = np.array([1, 2 ,3])
y = np.array([3, 2 ,1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [102]:
"""也可以一次性拼接两个以上的数组"""
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [103]:
"""np.concatenate也可以用于二维数组的拼接"""
grid = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [104]:
"""沿着第一个轴拼接"""
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [105]:
"""沿着第二个轴拼接（从0开始索引）"""
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

沿着固定纬度处理数组时， 使用np.vstack(垂直栈)和np.hstack(水平栈)函数会更加简洁

In [106]:
x = np.array([1, 2, 3])
grid = np.array([
    [9, 8, 7],
    [6, 5, 4]
])

In [107]:
"""垂直栈数组"""
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [108]:
"""水平栈数组"""
y = np.array([
    [99],
    [99]
])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [109]:
"""与之类似，np.dstack将沿第三个纬度拼接数组"""
x = np.array([
    [[11, 22], [22, 11]],
    [[33, 44], [44, 33]],
    [[55, 66], [66, 55]],
    [[77, 88], [88, 77]]
])

y = np.array([
    [[88, 77], [77, 88]],
    [[66, 55], [55, 66]],
    [[44, 33], [33, 44]],
    [[22, 11], [11, 22]]
])
np.dstack([x, y])

array([[[11, 22, 88, 77],
        [22, 11, 77, 88]],

       [[33, 44, 66, 55],
        [44, 33, 55, 66]],

       [[55, 66, 44, 33],
        [66, 55, 33, 44]],

       [[77, 88, 22, 11],
        [88, 77, 11, 22]]])

## 5.2 数组的分裂

与拼接想法的是分裂。分裂可以通过np.split，np.hsplit和np.vsplit函数来实现

可以向以上函数传递给一个索引列表作为参数，索引列表记录的是分裂点的位置

In [110]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


值得注意的是，N分裂点会得到N+1个子数组。相关的np.hsplit和np.vsplit的用法也类似

In [111]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [112]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [113]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [114]:
"""同样，np.dsplit将数组沿着第三个纬度分裂"""
grid = np.arange(27).reshape((3, 3, 3))
one, two, three = np.dsplit(grid, [1, 2])
print(grid)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [115]:
print(one)
print(two)
print(three)

[[[ 0]
  [ 3]
  [ 6]]

 [[ 9]
  [12]
  [15]]

 [[18]
  [21]
  [24]]]
[[[ 1]
  [ 4]
  [ 7]]

 [[10]
  [13]
  [16]]

 [[19]
  [22]
  [25]]]
[[[ 2]
  [ 5]
  [ 8]]

 [[11]
  [14]
  [17]]

 [[20]
  [23]
  [26]]]
