# 1. 缓慢的循环

In [1]:
# 计算每个元素的倒数
import numpy as np
np.random.seed(0)

def compute_reciprocal(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocal(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [2]:
# 当测试一个很大量的输入数据时，对求倒数这一操作进行测试
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocal(big_array)

1.74 s ± 10.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Python的默认实现（被称为CPython）处理其某些操作时非常缓慢
一部分原因是该语言的动态性和解释性
这里的处理瓶颈并不是运算本身，而是CPython在每次运算时必须做数据类型的检查和函数的调度
每次进行倒数运算时，Python首先检查对象的类型，并且动态查找可以使用该数据类型的正确函数

# 2. 通用函数介绍

NumPy提供了很多类型的向量操作，NumPy中的向量操作是通过通用函数实现的
对数组的操作会被用于数组的每一个元素
通用函数的目的是对NumPy数组中的值执行更快的操作

In [3]:
print(compute_reciprocal(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [4]:
"""标量与数组的运算"""
%timeit (1.0 / values)

956 ns ± 3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [5]:
"""对两个数组进行运算"""
np.arange(5) / np.arange(1 ,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [6]:
"""进行多维数组的运算"""
x = np.arange(9).reshape((3, 3))
x ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

# 3. 探索NumPy中的通用函数

## 3.1 数组的运算

In [7]:
"""加减乘除"""
x = np.arange(4)
print("x    =", x)
print("x + 5=", x + 5)
print("x - 5=", x - 5)
print("x * 2=", x * 2)
print("x / 2=", x / 2)
print("x // 2=", x // 2)  # 向下整除

x    = [0 1 2 3]
x + 5= [5 6 7 8]
x - 5= [-5 -4 -3 -2]
x * 2= [0 2 4 6]
x / 2= [0.  0.5 1.  1.5]
x // 2= [0 0 1 1]


In [8]:
"""求负数，指数运算与模运算"""
print("-x   =", -x)
print("x ** 2=", x ** 2)
print("x % 2 =", x % 2)

-x   = [ 0 -1 -2 -3]
x ** 2= [0 1 4 9]
x % 2 = [0 1 0 1]


所有这些算数运算符都是NumPy内置函数的简单封装器

In [9]:
"""加法运算"""
np.add(x, 2)

array([2, 3, 4, 5])

In [10]:
"""减法运算"""
np.subtract(x ,2)

array([-2, -1,  0,  1])

In [11]:
"""负数运算"""
np.negative(x)

array([ 0, -1, -2, -3])

In [12]:
"""乘法运算"""
np.multiply(x, 3)

array([0, 3, 6, 9])

In [13]:
"""除法运算"""
np.divide(x, 2)

array([0. , 0.5, 1. , 1.5])

In [14]:
"""向下整除运算"""
np.floor_divide(x, 2)

array([0, 0, 1, 1], dtype=int32)

In [15]:
"""指数运算"""
np.power(x, 2)

array([0, 1, 4, 9], dtype=int32)

In [16]:
"""模/余数"""
np.mod(x, 2)

array([0, 1, 0, 1], dtype=int32)

## 3.2 绝对值

In [17]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [18]:
"""绝对值对应的NumPy通用函数"""
print(np.absolute(x))
print(np.abs(x))

[2 1 0 1 2]
[2 1 0 1 2]


In [19]:
"""这个通用函数同样可以处理复数，当处理复数时，绝对值返回的是该复数的模"""
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

## 3.3 三角函数

In [20]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [21]:
"""三角函数"""
print("theta       =", theta)
print("sin(theta)  =", np.sin(theta))
print("cos(theta)  =", np.cos(theta))
print("tan(theta)  =", np.tan(theta))

theta       = [0.         1.57079633 3.14159265]
sin(theta)  = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta)  = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta)  = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [22]:
"""反三角函数"""
x = [-1, 0, 1]
print("x          =", x)
print("arcsin(x)  =", np.arcsin(x))
print("arccos(x)  =", np.arccos(x))
print("arctan(x)  =", np.arctan(x))

x          = [-1, 0, 1]
arcsin(x)  = [-1.57079633  0.          1.57079633]
arccos(x)  = [3.14159265 1.57079633 0.        ]
arctan(x)  = [-0.78539816  0.          0.78539816]


## 3.4 指数和对数

In [23]:
"""指数运算"""
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [24]:
"""对数运算"""
x = [1, 2, 4, 10]
print("x         =", x)
print("ln(x)     =", np.log(x))
print("log2(x)   =", np.log2(x))
print("log10(x)  =", np.log10(x))

x         = [1, 2, 4, 10]
ln(x)     = [0.         0.69314718 1.38629436 2.30258509]
log2(x)   = [0.         1.         2.         3.32192809]
log10(x)  = [0.         0.30103    0.60205999 1.        ]


In [25]:
"""一些特殊的版本，对于非常小的输入值可以保存良好的精度"""
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


## 3.5 专用的通用函数

当希望对数据进行更加晦涩的数学运算时，scipy.special可能包含需要的计算函数
下面的代码片段展示了一些可能在统计学中用到的函数

In [26]:
from scipy import special


"""Gamma函数(广义阶乘)和相关函数"""
x = [1, 5, 10]
print("gamma(x)      =", special.gamma(x))
print("ln|gamma(x)|  =", special.gammaln(x))
print("beta(x,2)     =", special.beta(x, 2))

gamma(x)      = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)|  = [ 0.          3.17805383 12.80182748]
beta(x,2)     = [0.5        0.03333333 0.00909091]


In [27]:
"""误差函数（高斯积分）  它的实现和它的逆实现"""
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)     =", special.erf(x))
print("erfc(x)    =", special.erfc(x))
print("erfinv(x)  =", special.erfinv(x))

erf(x)     = [0.         0.32862676 0.67780119 0.84270079]
erfc(x)    = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x)  = [0.         0.27246271 0.73286908        inf]


# 4. 高级的通用函数特性

## 4.1 指定输出

"""
在进行大量运算时，所有的通用函数都可以通过 out参数  来指定计算结果的存放位置
不同与创建临时数组，可以使用这个特性将计算结果直接写入你期望存放的存储位置
"""

In [28]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [29]:
"""这个特性也可以被用作数组视图，例如可以将计算结果直接写入指定数组的每隔一个元素的位置"""

y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)
"""如果这里写的是y[::2] = 2 ** x， 那么结果将是创建一个临时数组，该数组存放的是 2 ** x的结果，并且接下来会将这些值复制倒y数组中"""

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


'如果这里写的是y[::2] = 2 ** x， 那么结果将是创建一个临时数组，该数组存放的是 2 ** x的结果，并且接下来会将这些值复制倒y数组中'

## 4.2 聚合

二元通用函数有可以直接在对象上进行计算的聚合功能
例如：如果我们希望得到一个特定的运算 reduce 一个数组，
那么可以用任何通用函数的 reduce 方法。
一个reduce方法会对给定的元素和操作重复执行，直至得到单个的结果

In [30]:
"""返回数组中所有元素的和"""
x = np.arange(1, 6)
np.add.reduce(x)

15

In [31]:
"""返回数组中所有元素的乘积"""
np.multiply.reduce(x)

120

如果需要存储每次计算的中间结果，可以使用accumulate

In [32]:
"""相当存储每次累加的结果"""
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [33]:
"""相当存储每次累乘的结果"""
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

## 4.3 外积

任何通用函数都可以用 outer  方法获得两个不同输入数组所有元素对的函数运算结果。这意味着可以使用一行代码实现一个乘法表

In [34]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [35]:
np.add.outer(x, x)

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

In [36]:
np.subtract.outer(x, x)

array([[ 0, -1, -2, -3, -4],
       [ 1,  0, -1, -2, -3],
       [ 2,  1,  0, -1, -2],
       [ 3,  2,  1,  0, -1],
       [ 4,  3,  2,  1,  0]])